root: true
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  sourceType: module
  ecmaVersion: 2020
extends:
  - eslint:recommended
  - eslint-config-airbnb-base
  - plugin:import/recommended
  - plugin:jsdoc/recommended
  - prettier
plugins:
  - jsdoc
  - svelte3
ignorePatterns:
  - "*.cjs"
overrides:
  - files:
      - "*.svelte"
    processor: svelte3/svelte3
env:
  browser: true
  es2017: true
  node: true
rules:
  class-methods-use-this: off
  import/extensions: off
  import/first: off
  import/no-extraneous-dependencies: off
  import/no-mutable-exports: off
  import/no-unresolved: off
  import/prefer-default-export: off
  jsdoc/no-undefined-types: off
  jsdoc/require-jsdoc:
    - warn
    - require:
        ArrowFunctionExpression: true
        ClassDeclaration: true
        ClassExpression: true
        FunctionDeclaration: true
        FunctionExpression: true
        MethodDefinition: true
  jsdoc/valid-types: off
  max-len:
    - error
    - code: 100
      tabWidth: 2
      ignoreUrls: true
      ignoreStrings: true
  no-param-reassign: off
  # https://svelte.dev/docs#component-format-script
  no-undef-init: off
  no-underscore-dangle: off
  # https://github.com/airbnb/javascript/issues/1660#issuecomment-353018874 + small tweaks
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: "*"
      next:
        - block
        - block-like
        - cjs-export
        - class
        - const
        - export
        - import
        - let
        - var
    - blankLine: always
      prev:
        - block
        - block-like
        - cjs-export
        - class
        - const
        - export
        - import
        - let
        - var
      next: "*"
    - blankLine: never
      prev:
        - singleline-const
        - singleline-let
        - singleline-var
      next:
        - singleline-const
        - singleline-let
        - singleline-var
    - blankLine: any
      prev:
        - export
        - import
      next:
        - export
        - import
