# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Got a question?
    url: https://github.com/sveltia/sveltia-cms/discussions/new?category=q-a
    about: >
      If you cannot find the answer to your question in the README, you may ask for help in the
      discussion forum. Please note that, since Sveltia CMS is currently intended for existing
      Netlify/Decap CMS users, we do not offer free installation/setup support.
